GerenciadorSJD/Controllers/PoliciaisController.cs
using GerenciadorSJD.Models;
using GerenciadorSJD.Service;
using GerenciadorSJD.Service.Exceptions;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using GerenciadorSJD.Models.ViewModel;

namespace GerenciadorSJD.Controllers
{
    public class PoliciaisController : Controller
    {
        private readonly ServicePolicia _servicepolicia;
        private readonly ServiceProcesso _serviceprocesso;

        public PoliciaisController(ServicePolicia servicepolicia, ServiceProcesso serviceprocesso)
        {
            _servicepolicia = servicepolicia;
            _serviceprocesso = serviceprocesso;
        }

        public async Task<IActionResult> Index()
        {
            var lista = await _servicepolicia.RetornarTodos();
            return View(lista);
        }

        public async Task<IActionResult> BuscaSimples(string re)
        {
            var resultado = await _servicepolicia.PesquisarReNomeAsync(re);
            return View(resultado);
        }

        public async Task<IActionResult> Create()
        {           
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Policia pm)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await _servicepolicia.InserirAsync(pm);
                    return RedirectToAction(nameof(Index));
                }

                catch (ExcNotFound e)
                {
                    return RedirectToAction(nameof(Error), new { mensagem = e.Message });
                }
            }
            return View(pm);            
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { mensagem = "Id não fornecido" });
            }
            var obj = await _servicepolicia.RetornarPolicialIdAsync(id.Value);
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { mensagem = "Id inexistente" });
            }

            List<Processo> processo = await _serviceprocesso.RetornarTodosAsync();
            ModeloPolicial viewModelo = new ModeloPolicial { Policiais = obj, Processos = processo };
            return View(viewModelo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Policia pm)
        {
            if (!ModelState.IsValid)
            {
                var processos = await _serviceprocesso.RetornarTodosAsync();
                var novaView = new ModeloPolicial { Policiais = pm, Processos = processos };
                return View(novaView);
            }
            if (id != pm.Id)
            {
                return RedirectToAction(nameof(Error), new { mensagem = "Id não corresponde." });
            }
            try
            {
                await _servicepolicia.EditarAsync(pm);
                return RedirectToAction(nameof(Index));
            }
            catch (ExcNotFound e)
            {
                return RedirectToAction(nameof(Error), new { mensagem = e.Message });
            }
            catch (ExcBd e)
            {
                return RedirectToAction(nameof(Error), new { mensagem = e.Message });
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { mensagem = "Id não fornecido" });
            }

            var obj = await _servicepolicia.RetornarPolicialIdAsync(id.Value);

            if(obj == null)
            {
                return RedirectToAction(nameof(Error), new { mensagem = "Cadastro inexistente" });
            }
            return View(obj);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { mensagem = "Id não fornecido" });
            }

            var obj = await _servicepolicia.RetornarPolicialIdAsync(id.Value);

            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { mensagem = "Cadastro inexistente" });
            }
            return View(obj);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _servicepolicia.RemoveAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (ExcIntegridade e)
            {
                return RedirectToAction(nameof(Error), new { mensagem = e.Message });
            }
        }



        public IActionResult Error(string mensagem)
        {
            var modeloErro = new ErrorViewModel
            {
                Message = mensagem,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(modeloErro);
        }
               
    }
}

GerenciadorSJD/Views/Shared/_Layout.cshtml
@{
    ViewData["AnoAtual"] = DateTime.Now.Year;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GerenciadorSJD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-zephyr.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GerenciadorSJD.styles.css" asp-append-version="true" />      
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info bg-opacity-10 border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciador - SPJMD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Policiais" asp-action="Index">Policiais</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Oficiais" asp-action="Index">Oficiais</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Procedimentos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Procedimentos" asp-action="IP">IP</a>
                                <a class="dropdown-item" href="#">Sindicância</a>
                                <a class="dropdown-item" href="#">IPM</a>
                                <a class="dropdown-item" href="#">Apuração Preliminar</a>
                                <a class="dropdown-item" href="#">APFD</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Procedimentos" asp-action="Total">Todos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Procedimentos" asp-action="Index">Pesquisar</a>

                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-info bg-opacity-10">
        <div class="text-center text-muted "> @ViewData["AnoAtual"]  -  BUZZO &copy; Developer <a asp-area="" asp-controller="Home" asp-action="Privacy"></a></div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>